# Generated by Django 3.0.7 on 2020-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENCY', models.CharField(blank=True, max_length=100, null=True)),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('RESPMSG', models.CharField(blank=True, max_length=100, null=True)),
                ('BANKNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=100, null=True)),
                ('MID', models.CharField(blank=True, max_length=100, null=True)),
                ('RESPCODE', models.CharField(blank=True, max_length=100, null=True)),
                ('TXNID', models.CharField(blank=True, max_length=100, null=True)),
                ('TXNAMOUNT', models.CharField(blank=True, max_length=100, null=True)),
                ('ORDERID', models.CharField(blank=True, max_length=100, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('BANKTXNID', models.CharField(blank=True, max_length=100, null=True)),
                ('TXNDATE', models.CharField(blank=True, max_length=100, null=True)),
                ('CHECKSUMHASH', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
