# Generated by Django 3.0.7 on 2020-06-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ORDERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('bicycle', models.ForeignKey(default='bicycle', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Bicycle')),
                ('color', models.ForeignKey(default='color', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Color')),
            ],
        ),
    ]
